FROM parity/parity:v1.11.8

ENV PASSPHRASE=123456

ADD start.sh   /start.sh
ADD chain.json /chain.json
ADD key0.json  /eth/keys/Private/key0.json
ADD key1.json  /eth/keys/Private/key1.json

RUN chmod +x /start.sh && \
    echo ${PASSPHRASE} > /.parity-pass

ENTRYPOINT /start.sh

# 0x00fc9af07fb2fcfc560672630b19bb8f72732164
# sequence retainer probable always harmonics valiant parasitic imply worried reload flashy chowder
# sequence retainer probable always harmonics valiants parasitic imply worried reload flashy chowder

# I have written down the phrase

# 0x006Db1ebe1D7da13Aa4B7523F7A4Ff123Cf98E58
# oppressor pristine dazzling juicy headstone ruby unworldly arrogance amiss budget tank dismiss
# oppressor pristine dazzling juicy headstone ruby unworldly arrogance amiss budget tank dismiss