CREATE TABLE blocks (
  "number" INT UNIQUE NOT NULL DEFAULT 0 PRIMARY KEY,
  block_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);